### ISSUE TITLE
Log-In Screen

### ISSUE THREAD

**Issue by vutk3** [vcu-cmsc355-f17/android-app-alt-tab#10]
As a user,
So that I can be able do activities within the app under my name,
I want to be able to log into the app

Feature: Logging in
Scenario: Successful Log-In
Given that I am on the user log-in page
When I select my email at Google sign in
And I click on the "Sign in" button
Then I should be able to log into my account
And I should be taken to my home page

Scenario: Unsuccessful Log-In
Given that I am on the user log-in page
When I cancel Google login
And I click on the "Sign in" button
Then I should see a message saying "Error: Incorrect username/password"
And I should be prompted to type in another username and password

Scenario: Logging in using Google
Given that I am on the user log-in page
When I click on the "Use Facebook" button
Then I should be prompted to type in my Facebook username and password

**Comment by adelShahrezaei** [comment]
TODO: 

- [x] make scaffolding 
- [x] setup firebase auth
- [ ] design UI
- [ ] first time login user should be able to choose display name
