### ISSUE TITLE
Initiating Story

### ISSUE THREAD

**Issue by hemanbaral** [vcu-cmsc355-f17/android-app-alt-tab#5]
# Initiating Story
As a user,
So that other people can add on to my story,
I want to be able create a story

**Feature**: Start your own story

**Scenario**: Story tab 

Given I am on my main page screen
When I click on the "Create Story" button
Then a new page should open where I can write my story

**Scenario**: Title and Story

Given that I am on the "Create Story" page
When I click on the "Title" and "Story" textboxes
And I type in some text
Then I should be able to click on the "Submit" button
And I should be directed back to the main screen

**Scenario**: Didn't write any text

Given that I am on the "Create Story" page
When I click on the "Submit" button
And I haven't typed in any text in the "Title"  textbox
Then the "Submit" button should not work
And I cannot submit my story until the textbox is filled

**Comment by vutk3** [comment]
Tests were given the name of its corresponding scenario
