### ISSUE TITLE
Adding to Stories

### ISSUE THREAD

**Issue by hemanbaral** [vcu-cmsc355-f17/android-app-alt-tab#6]
# Adding to Stories
As a contributor,
So that I can help complete a story,
I want to be able to add some text to an unfinished story

**Feature**: Other users can contribute to the story

**Scenario**: Any user can contribute (Add proper scenario)

Given that I am on an unfinished story page
When I click on the text box at the bottom of the screen
And I enter some text
And I click the "Send" button 
Then I should be able to add my lines to the story

**Scenario**: Adding too much text (Too much add)

Given that I am on an unfinished story page
When I try to add over 50 characters to a story
Then I should not be able to type past the 50 characters

**Scenario**: Cant add no text (No add)

Given that I am on an unfinished story page
When I click on the "Add Text" button 
Then the app should not output anything

**Comment by adelShahrezaei** [comment]
- [x] add chunk (model)
- [x] get chunk from db 
- [ ] insert chunk to db 
- [ ] add chunk View (input, view)
- [ ] add
